April Mockingbird patch
tinybirdco/mockingbird pull request #86
Opened 2024-08-01 22:35 UTC by april-tinybird

Add AWS regions to Host dropdown for Mockingbird Tinybird Events API Settings to eliminate need to specify Endpoint with Custom.

https://www.tinybird.co/docs/api-reference/overview#regions-and-endpoints
<img width="800" alt="Screenshot 2024-08-01 at 17 50 13" src="https://github.com/user-attachments/assets/5ebd90de-c6bf-47b2-9466-be8c1e01fb6a">

2024-08-01 22:41 UTC, april-tinybird commented
@sdairs @davidnmargulies I think I accidentally tried a pull request without asking for approvers first which is why the Vercel bot is mad

2024-08-01 23:31 UTC, davidnmargulies approved these changes

2024-08-02 12:42 UTC, sdairs commented
iirc this will fail cause the npm package needs to be updated & published first, then the UI updated to use the latest package

2024-08-02 12:43 UTC, sdairs requested changes
Separate changes; do the package update first and publish to npm, then do a new PR to update the UI (and then we need to follow up with CLI as well & publish it)

2024-08-02 12:47 UTC, sdairs commented on packages/mockingbird/src/generators/TinybirdGenerator.ts
> +    gcp_us_east4': "https://api.us-east.tinybird.co",
syntax typo here

2024-08-02 12:49 UTC, sdairs commented
split out the package changes to a new PR here https://github.com/tinybirdco/mockingbird/pull/87

2024-08-02 13:43 UTC, sdairs approved these changes
lgtm

2024-08-02 13:45 UTC, merged